# ###### In case you forget...
# :ro === :readonly
# for each 'ports' entry -> HOST_PORT:CONTAINER_PORT

services:
  sandbox-server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: sandbox
    ports:
      - "1234:1234"
    volumes:
      - ./server:/opt/server
      - /opt/server/node_modules
